local HWFF = require "DWAP_HWFF/configs/DWAP_HogWallowFacility"
print("DWAP HWFF extraLoot.lua loaded")
local extraLoot = {
    -- big warehouse room level -13
    {
        type = 'container',
        coords = { x = 5522, y = 12483, z = -13 },
        items = {
            { name = 'Base.Bag_ProtectiveCaseBulkyHazard', },
            { name = 'Base.Hat_NBCmask', },
            { name = 'Base.Glasses_SafetyGoggles', },
            { name = 'Base.Hat_BuildersRespirator', },
            { name = 'Base.HazmatSuit', },
            { name = 'Base.RespiratorFilters', },
            { name = 'Base.Hat_GasMask', },
            { name = 'Base.GasmaskFilter', },
        },
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 5523, y = 12483, z = -13 },
        items = {
            { name = 'Base.Oxygen_Tank', },
        },
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 5524, y = 12483, z = -13 },
        dist = { "MorgueTools", "LaboratoryLockers", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = { x = 5525, y = 12483, z = -13 },
        dist = { "ArmyStorageMedical", "ArmyBunkerMedical" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_MedLevel",
    },
    {
        type = 'container',
        coords = { x = 5522, y = 12486, z = -13 },
        dist = { "CrateVHSTapes", "MovieRentalShelves" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_MediaLevel",
    },
    {
        type = 'container',
        coords = { x = 5523, y = 12486, z = -13 },
        dist = { "GardenStoreTools", "Homesteading", "ToolStoreFarming", "CrateFarming" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 5524, y = 12486, z = -13 },
        items = {
            { name = 'Base.Fertilizer', chance = 1, count = { 8, 10 } },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 5525, y = 12486, z = -13 },
        items = {
            { name = 'Base.AnimalFeedBag', chance = 1, count = { 9, 12 } },
        },
        randUntilFull = true,
        level = "Loot_FarmLevel",
    },
    {
        type = 'container',
        coords = { x = 5522, y = 12489, z = -13 },
        dist = { "CrateFishing", "FishermanTools" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FishLevel",
    },
    {
        type = 'container',
        coords = { x = 5523, y = 12489, z = -13 },
        dist = { "CrateLiquor" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5524, y = 12489, z = -13 },
        dist = { "SewingStoreFabric" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    {
        type = 'container',
        coords = { x = 5525, y = 12489, z = -13 },
        dist = { "SewingStoreTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_TailorLevel",
    },
    {
        type = 'container',
        coords = { x = 5522, y = 12493, z = -13 },
        dist = { "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateLinens" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 5523, y = 12493, z = -13 },
        dist = { "ArmyStorageOutfit", "DrugLabOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "ToolStoreOutfit" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 5524, y = 12493, z = -13 },
        dist = { "ArmyStorageOutfit", "LockerArmyBedroom", "LockerArmyBedroomHome", "ArmySurplusOutfit", "CrateBootsArmy" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_LockersLevel",
    },
    {
        type = 'container',
        coords = { x = 5525, y = 12493, z = -13 },
        dist = { "CampingLockers" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 5522, y = 12496, z = -13 },
        dist = { "CampingStoreBackpacks" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 5523, y = 12496, z = -13 },
        dist = { "GunStoreKnives", "PawnShopKnives", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 5524, y = 12496, z = -13 },
        dist = { "SafehouseTraps", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 5525, y = 12496, z = -13 },
        dist = { "ArmyStorageAmmunition", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_GunLevel",
    },
    {
        type = 'container',
        coords = { x = 5522, y = 12499, z = -13 },
        dist = { "CarSupplyTools", "GasStorageMechanics", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5523, y = 12499, z = -13 },
        dist = { "CampingStoreTools", "ArmyHangarTools", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5524, y = 12499, z = -13 },
        dist = { "BurglarTools", "CarpenterTools", "BarnTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5525, y = 12499, z = -13 },
        dist = { "CrateTools", "GarageTools", "BarnTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5527, y = 12493, z = -13 },
        dist = { "GigamartTools", "JanitorTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5528, y = 12493, z = -13 },
        dist = { "LoggingFactoryTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5529, y = 12493, z = -13 },
        dist = { "CrateRandomJunk", "RandomFiller", "ArmySurplusMisc" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = 3,
    },
    {
        type = 'container',
        coords = { x = 5530, y = 12493, z = -13 },
        dist = { "CrateCannedFood", "ArmySurplusTools" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5527, y = 12496, z = -13 },
        dist = { "CrateRandomJunk", "RandomFiller" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = 3,
    },
    {
        type = 'container',
        coords = { x = 5528, y = 12496, z = -13 },
        dist = { "CrateCannedFood", "RandomFiller" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5529, y = 12496, z = -13 },
        dist = { "ArmyStorageElectronics", "RandomFiller" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5530, y = 12496, z = -13 },
        dist = { "ToolFactoryHandles" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5527, y = 12499, z = -13 },
        dist = { "ToolFactoryIngots" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5528, y = 12499, z = -13 },
        dist = { "CrateSheetMetal" },
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5529, y = 12499, z = -13 },
        dist = { "CrateLumber" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5530, y = 12499, z = -13 },
        dist = { "CrateLumber" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5532, y = 12493, z = -13 },
        dist = { "CrateLumber", "CrateSheetMetal" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5533, y = 12493, z = -13 },
        dist = { "WeldingWorkshopMetal" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5534, y = 12493, z = -13 },
        dist = { "WeldingWorkshopMetal" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5535, y = 12493, z = -13 },
        items = {
            { name = 'Base.NailsCarton', },
        },
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5532, y = 12496, z = -13 },
        items = {
            { name = 'Base.NailsBox', },
            { name = 'Base.ScrewsBox', },
        },
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5533, y = 12496, z = -13 },
        dist = { "ToolFactoryBarStock", "ToolFactoryHandles", "WeldingWorkshopMetal", "ToolFactoryIngots" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_BuildMatsLevel",
    },
    {
        type = 'container',
        coords = { x = 5534, y = 12496, z = -13 },
        dist = { "StoreCounterTobacco" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5535, y = 12496, z = -13 },
        dist = { "GasStoreEmergency" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_ToolsLevel",
    },
    {
        type = 'container',
        coords = { x = 5532, y = 12499, z = -13 },
        dist = { "CrateFlour", "CrateOilVegetable" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5533, y = 12499, z = -13 },
        dist = { "CandyStoreSnacks" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5534, y = 12499, z = -13 },
        dist = { "CrateTortillaChips" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5535, y = 12499, z = -13 },
        dist = { "StoreShelfDrinks", "FridgeSoda", "CrateSodaBottles" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- kitchen storage room level -15
    {
        type = 'container',
        coords = { x = 5562, y = 12481, z = -15 },
        dist = { "CrepeKitchenBaking", "CrepeKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5562, y = 12482, z = -15 },
        dist = { "WesternKitchenBaking", "WesternKitchenSauce", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5562, y = 12483, z = -15 },
        dist = { "FishChipsKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5562, y = 12484, z = -15 },
        dist = { "ItalianKitchenBaking", "ItalianKitchenSauce", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5562, y = 12485, z = -15 },
        dist = { "ArenaKitchenSauce", "ArmyBunkerKitchen", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5562, y = 12486, z = -15 },
        dist = { "JaysKitchenBaking", "BakeryKitchenFreezer" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5565, y = 12481, z = -15 },
        dist = { "JaysKitchenSauce", "JerkyFactorySpices" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5566, y = 12481, z = -15 },
        dist = { "JerkyFactoryCrate" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5567, y = 12481, z = -15 },
        dist = { "KitchenBaking" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5568, y = 12481, z = -15 },
        dist = { "KitchenBottles" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5565, y = 12483, z = -15 },
        dist = { "KitchenBreakfast" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5566, y = 12483, z = -15 },
        dist = { "KitchenCannedFood" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5567, y = 12483, z = -15 },
        dist = { "KitchenDryFood" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5568, y = 12483, z = -15 },
        dist = { "KitchenRandom" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5565, y = 12485, z = -15 },
        dist = { "MexicanKitchenSauce", "MexicanKitchenBaking", },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5566, y = 12485, z = -15 },
        dist = { "PizzaKitchenBaking", "PizzaKitchenCheese", "PizzaKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5567, y = 12485, z = -15 },
        dist = { "SeafoodKitchenSauce", "SpiffosKitchenSauce" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5568, y = 12485, z = -15 },
        dist = { "SpiffosKitchenBaking" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5565, y = 12487, z = -15 },
        dist = { "StoreKitchenBaking" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5566, y = 12487, z = -15 },
        dist = { "StoreKitchenCafe" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5567, y = 12487, z = -15 },
        dist = { "StoreKitchenCleaning" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5568, y = 12487, z = -15 },
        dist = { "StoreKitchenPotatoes" },
        distIncludeJunk = true,
        randUntilFull = true,
        level = "Loot_FoodLevel",
    },
    -- fridges
    {
        type = 'container',
        coords = { x = 5565, y = 12488, z = -15 },
        dist = {"CrateButter"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
        frozen = true,
    },
    {
        type = 'container',
        coords = { x = 5566, y = 12488, z = -15 },
        dist = {"CrateButter"},
        distIncludeJunk = false,
        randUntilFull = true,
        level = "Loot_FoodLevel",
        frozen = true,
    },
    {
        type = 'container',
        coords = { x = 5567, y = 12488, z = -15 },
        dist = {"FreezerIceCream", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
    {
        type = 'container',
        coords = { x = 5568, y = 12488, z = -15 },
        dist = {"CafeteriaKitchenFreezer", },
        distIncludeJunk = false,
        randUntilFull = true,
        frozen = true,
        level = "Loot_FoodLevel",
    },
}

if HWFF and HWFF.loot then
    for i = 1, #extraLoot do
        table.insert(HWFF.loot, extraLoot[i])
    end
end

return HWFF
